[package]
name = "mosaic"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
libc = "0.2.176"
reqwest = "0.12.23"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
